### PR TITLE
Add Xcode 7.1 UUID

### PR DESCRIPTION
**Pull request by revolter**

### CODE REVIEW

**Comment by yuhua-chen** [comment]
Thank you so much! :beers:

**Comment by revolter** [comment]
My pleasure! I created an `alias` that prints the installed Xcode's UUID:

    alias xuuid='defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID'

You can use this for later updates.

**Comment by yuhua-chen** [comment]
It's really helpful. Thanks :+1:

**Comment by kanekin** [comment]
XCode crashes every time on launch after adding alias. It keeps crashing after removing the alias.
I am using XCode7.1 on OSX 10.11.1

**Comment by revolter** [comment]
@kanekin, What "alias" are you talking about?

**Comment by kanekin** [comment]
The alias you mentioned above. 
```
alias xuuid='defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID'
```

**Comment by revolter** [comment]
That is not the fix, the fix is the pull request's commit.

**Comment by kanekin** [comment]
I see, sorry for not reading the thread properly. But XCode still crashes after re-installing MCLog with Alcatraz. Is Alcatraz supposed to pick the latest commit on master branch?

**Comment by yuhua-chen** [comment]
I believe Alcatraz did pick up latest commit from master branch. I'm working on issue #33. we can move the discussion to that thread.

**Pull request merged**
